[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psutil==5.9.8",
    "pyrogram==2.0.106",
    "pytgcalls>=3.0.0.dev24",
    "python-dotenv==1.0.1",
    "tgcrypto==1.2.5",
    "pillow==10.4.0",
    "qrcode==7.4.2",
    "python-barcode==0.15.1",
    "yt-dlp>=2025.1.0",
    "aiosqlite",
]
