"""
IBEKS USERBOT - Fun Plugin Data
Kumpulan data lucu untuk command .ctampan dan .ccantik.
Setiap kategori memiliki minimal 50 item.
"""

# ── CTAMPAN (Cek Tampan) ─────────────────────────────────────────────────────

CTAMPAN_AURA = [
    "Bad Boy WiFi Gratis",
    "Senyum Bikin Satpam Bingung",
    "Wajah Anime Budget Pas-pasan",
    "Aura Sultan Kontrakan",
    "Raja Nongkrong Indomaret",
    "Tatapan Bikin Galon Minder",
    "Glowing Karena Minyak Wajah",
    "Aura Jutek tapi Tetep Bikin Kepo",
    "Pede Level Kang Parkir",
    "Aura Jomblo tapi Gaya Raja",
    "Senyum Bikin Lampu Jalan Redup",
    "Tatapan Bikin HP Panas",
    "Aura Ganteng dari Luar Angkasa",
    "Gaya Bintang Sinetron Gepeng",
    "Aura Cowok Idaman Mertua (Tapi Ibumu Dulu)",
    "Pesona Pria Jumat Berkah",
    "Aura Bikin Tetangga Ingin Pindah",
    "Tatapan Bikin Kulkas Buka Sendiri",
    "Glowing Seperti Neon Warteg",
    "Aura Sultan Tapi Dompet Akhir Bulan",
    "Senyum Bikin Pengendara Macet Lihat",
    "Gaya Anak Tongkrongan Tapi Berkelas",
    "Aura Pria yang Dicari Satpam",
    "Tatapan Bikin CCTV Jatuh Cinta",
    "Aura Kapten Futsal Pinggir Jalan",
    "Glowing Karena Flash Kamera HP",
    "Pesona Kang Baso Tampan",
    "Aura Duda Muda Idaman",
    "Senyum Bikin Bunga Layu Mekar",
    "Gaya Raja Jalanan",
    "Aura Bikin Anak Kecil Minta Selfie",
    "Tatapan Bikin Gorden Tertiup",
    "Glowing Kayak Papan Reklame",
    "Aura Cowok yang Dicari Ibu-ibu Komplek",
    "Pesona Bintang Iklan Sabun Colek",
    "Aura Bikin Motor Mogok Melihat",
    "Senyum Bikin Tukang Bakso Gratis",
    "Gaya Pangeran Kos-kosan",
    "Aura Jutek Tapi Sayang Anak Kucing",
    "Tatapan Bikin Es Batu Meleleh",
    "Glowing Seperti Lampu Warung",
    "Aura Sultan Mie Instan",
    "Senyum Bikin Janda Kembang Ceria",
    "Gaya Model Katalog Online Murah",
    "Aura Bikin Tukang Parkir Hormat",
    "Tatapan Bikin Angin Berhenti Tiup",
    "Glowing Karena Keringat Usaha",
    "Aura Cowok Penakluk Hati Ibu-Ibu",
    "Pesona Raja Jalan Raya",
    "Aura Bikin Satpam Lupa Jam Pulang",
    "Bad Boy Kantin Sekolah",
    "Pangeran Kali Berdasi",
]

CTAMPAN_PENAMPILAN = [
    "Kaos Oblong + Sendal Jepit = Auto Keren",
    "Rambut Kayak Habis Kena Angin Tornado",
    "Outfit Murah Tapi Gayanya Mewah",
    "Glowing Walau Baru Bangun",
    "Wangi Parfum Tester Mall",
    "Fashion Sultan Akhir Bulan",
    "Celana Sobek Karena Gaya Bukan Karena Jatuh",
    "Kemeja Batik Dipakai ke Konser",
    "Jam Tangan Palsu Tapi Pede Asli",
    "Sepatu Putih Bersih ala Bintang Iklan",
    "Rambut Dicat dari Sisa Cat Tembok",
    "Jaket Kulit dari Pasar Malam",
    "Style Bapak-Bapak tapi Bikin Meleleh",
    "Kacamata Hitam di Dalam Ruangan",
    "Outfit Ala Anak Skena 2010",
    "Celana Cargo Isi Penuh Barang",
    "Rambut Gimbal Aesthetic",
    "Kaos Band yang Tidak Pernah Didengar",
    "Sendal Swallow tapi Gayanya Sneakers",
    "Hoodie Boba Tapi Bukan Boba",
    "Kemeja Putih Glowing Seperti Tuyul",
    "Celana Chino Disanggakan Pinggang",
    "Rambut Pomade Seperti Komplotan 90-an",
    "Outfit Thrifting Tapi Kelihatan Sultan",
    "Jam Tangan Digital ala Anak SD",
    "Kaos Polos Tapi Vibe-nya Mahal",
    "Celana Jeans Ketat Bak Cabor",
    "Rambut Kribo Aesthetic Abis",
    "Jaket Bomber dari Zaman SMA",
    "Kaus Kaki Naik ke Mata Kaki",
    "Sneakers Putih Bikin Iri Sekampung",
    "Kacamata Minus Dipakai Pamer",
    "Outfit Hemat Tapi Instagramable",
    "Rambut Slick Back ala Dono",
    "Kaos Polo Ala Sales Mobil",
    "Celana Training Warna Warni",
    "Jaket Denim Klasik",
    "Topi Snapback Terbalik",
    "Kemeja Flanel ala Pemburu",
    "Rambut Undercut Tanpa Pomade",
    "Sendal Jepit tapi Berjalan Penuh Percaya Diri",
    "Outfit One Set dari Thrift Shop",
    "Tas Slempang Selempang Hati",
    "Kacamata Anti Radiasi Pameran",
    "Rambut Panjang Berantakan Aesthetic",
    "Kaos Oversize Menutupi Celana",
    "Celana Pendek ala Anak Kost",
    "Jam Tangan Pintar Tapi Baterai Habis",
    "Sepatu Crocs dengan Jibbitz Keren",
    "Jaket Hoodie Bertuliskan Quotes Galau",
    "Kemeja Linen Berantakan Aesthetic",
]

CTAMPAN_KEUNGGULAN = [
    "Senyum Bikin Nyamuk Ikut Jatuh Cinta",
    "Tatapan Bikin CCTV Fokus",
    "Muka Bikin Kamera Auto HD",
    "Jalan Dikira Selebgram",
    "Bikin Tetangga Kepo",
    "Aura Positif 1000 Watt",
    "Gagal Jelek Sejak Lahir",
    "Senyum Bikin Hari Jumat Lebih Berkah",
    "Tatapan Bikin Bensin Motor Penuh",
    "Muka Bikin Warung Tambah Laku",
    "Jalan Bikin Orang Lupa Jalan",
    "Bikin Satpam Komplek Ingin Kenalan",
    "Aura Bikin Galon Air Hangat",
    "Senyum Bikin Tukang Parkir Gratis",
    "Tatapan Bikin Lampu Belajar Lebih Terang",
    "Muka Bikin HP Baterai Awet",
    "Jalan Bikin Macet Jadi Lupa",
    "Bikin Ibu-Ibu Warung Tersipu",
    "Aura Bikin Es Teh Manis Lebih Manis",
    "Senyum Bikin Kucing Ikut Mengeong",
    "Tatapan Bikin Anak SD Pengen Pinter",
    "Muka Bikin Fotografer Jalanan Aktif",
    "Jalan Bikin Orang Lupa Tujuan",
    "Bikin Teman Lama Ingin Reuni",
    "Aura Bikin Pom Bensin Buka 24 Jam",
    "Senyum Bikin Tukang Cilok Gratis",
    "Tatapan Bikin Angin Berhenti Sejenak",
    "Muka Bikin Kamera Depan Jadi HD",
    "Jalan Bikin Jalanan Terasa Runway",
    "Bikin Penjual Martabak Tambah Sayang",
    "Aura Bikin Warteg Ramai Pengunjung",
    "Senyum Bikin Hari Senin Lebih Terang",
    "Tatapan Bikin WiFi Full Bar",
    "Muka Bikin Orang Lupa Marah",
    "Jalan Bikin Jalanan Jadi Panggung",
    "Bikin Teman Sekelas Ingin Contek",
    "Aura Bikin Musim Hujan Jadi Cerah",
    "Senyum Bikin Tukang Sate Tidak Tega Potong",
    "Tatapan Bikin Emak-Emak Terpesona",
    "Muka Bikin Kamera Rusak Jadi Bagus",
    "Jalan Bikin Orang Lupa Waktu",
    "Bikin Tukang Cukur Ingin Gratis",
    "Aura Bikin Indomaret Makin Indah",
    "Senyum Bikin Tukang Tambal Ban Cepat",
    "Tatapan Bikin Lampu Merah Jadi Hijau",
    "Muka Bikin Orang Lupa Hutang",
    "Jalan Bikin Gojek Tepat Waktu",
    "Bikin Tukang Bakso Tanya Nomor",
    "Aura Bikin Galon Jadi Penuh",
    "Senyum Bikin Semua Orang Tersenyum",
    "Gaya Bikin Orang Lupa Kalau Lagi Marah",
]

CTAMPAN_TIER = [
    "PACAR MERTUA",
    "SULTAN KONTRAKAN",
    "CEO WARUNG MADURA",
    "RAJA WIFI RT",
    "PANGERAN KONTER PULSA",
    "KING OF OBLONG",
    "QUEEN KOS-KOSAN",
    "BOS ES TEH",
    "KOMANDAN RONDA",
    "ANAK EMAS WARUNG",
    "PENAKLUK KANTIN",
    "SULTAN GALON",
    "BOSS PARKIR",
    "RAJA JALAN RAYA",
    "SULTAN SPBU",
    "KAPten FUTSAL PINGGIR JALAN",
    "DIREKTUR WARTEG",
    "MANAGER INDOMARET",
    "KOMANDAN PARKIRAN",
    "RAJA NONGKRONG",
    "SULTAN KARCIS",
    "BOSS PARKIR MOTOR",
    "KAPten GALON",
    "DIREKTUR KOS-KOSAN",
    "MANAGER ANGKRINGAN",
    "RAJA WIFI GRATIS",
    "SULTAN PULSA",
    "BOSS KANTIN",
    "KAPten BASO",
    "DIREKTUR ES TEH",
    "MANAGER TAHU BULAT",
    "RAJA SEBLAK",
    "SULTAN CILOK",
    "BOSS KETOPRAK",
    "KAPten MARTABAK",
    "DIREKTUR BAKSO",
    "MANAGER SATE",
    "RAJA NASI GORENG",
    "SULTAN BUBUR AYAM",
    "BOSS GADO-GADO",
    "KAPten PEMPEK",
    "DIREKTUR PADANG",
    "MANAGER AYAM GEPREK",
    "RAJA MIE AYAM",
    "SULTAN BAKMI",
    "BOSS SOTO",
    "KAPten RONDA MALAM",
    "DIREKTUR KONTER HP",
    "MANAGER WARNET",
    "RAJA JALANAN",
    "SULTAN PARKIRAN",
    "BOSS KANG PARKIR",
]


# ── CCANTIK (Cek Cantik) ─────────────────────────────────────────────────────

CCANTIK_AURA = [
    "Bidadari Salah Alamat",
    "Princess Alfamart",
    "CEO Kantin Sekolah",
    "Dewi Diskon Shopee",
    "Miss RT 08",
    "Senyum Bikin Tukang Parkir Lupa Karcis",
    "Tatapan Bikin Gorden Buka Sendiri",
    "Glowing Karena Bedak Murah",
    "Aura Putri Kerajaan Kios",
    "Ratu Nongkrong Warteg",
    "Senyum Bikin Satpam Tersipu",
    "Tatapan Bikin HP Auto Selfie",
    "Aura Bintang Iklan Susu",
    "Gaya Gadis Pinggiran Instagram",
    "Aura Bikin Emak-Emak Ingin Jadi Menantu",
    "Pesona Putri Kos-kosan",
    "Senyum Bikin Lampu Jalan Lebih Terang",
    "Tatapan Bikin Kulkas Buka Sendiri",
    "Glowing Seperti Pelangi Cuaca Panas",
    "Aura Sultan THR",
    "Senyum Bikin Pengendara Ojek Menepi",
    "Gaya Anak Skena Tapi Cantiknya Polos",
    "Aura Gadis yang Dicari Semua RT",
    "Tatapan Bikin CCTV Berputar",
    "Aura Ratu Jalanan",
    "Glowing Karena Krim Siang Malam",
    "Pesona Bidadari Warung Kopi",
    "Aura Janda Muda Idaman",
    "Senyum Bikin Bunga di Trotoar Mekar",
    "Gaya Putri Kerajaan Pinggir Kali",
    "Aura Bikin Anak Kecil Ingin Dipeluk",
    "Tatapan Bikin Angin Berhenti Sejenak",
    "Glowing Kayak Papan Nama Toko",
    "Aura Cewek yang Dicari Tukang Bakso",
    "Pesona Bintang Iklan Minyak Goreng",
    "Aura Bikin Motor Berhenti Mogok",
    "Senyum Bikin Tukang Sayur Gratis",
    "Gaya Putri Raja Jalanan",
    "Aura Jutek Tapi Sayang Anak Kucing",
    "Tatapan Bikin Es Batu Meleleh",
    "Glowing Seperti Lampu Salon",
    "Aura Sultan Voucher GoFood",
    "Senyum Bikin Duda Kembang Semangat",
    "Gaya Model Bule Di-Kapur",
    "Aura Bikin Tukang Parkir Senyum",
    "Tatapan Bikin Angin Berhenti Tiup",
    "Glowing Karena Keringat Joging",
    "Aura Cewek Penakluk Hati Semua",
    "Pesona Ratu Jalan Raya",
    "Aura Bikin Satpam Lupa Jam Pulang",
    "Dewi Diskon Tokopedia",
    "Ratu Jalanan Berdaster",
]

CCANTIK_PENAMPILAN = [
    "Daster + Sendal Jepit = Ratu Jalanan",
    "Rambut Kuncir Dua ala Anak TK",
    "Outfit Murah Tapi Gayanya Mahal",
    "Glowing Walau Baru Bangun Tidur",
    "Wangi Parfum Bisa Dibeli di Alfamart",
    "Fashion Sultan Akhir Bulan",
    "Rok Mini Bikin Hati Berdebar",
    "Blus Putih Bersih ala Bintang Iklan",
    "Rambut Dicat dari Warna Tembok",
    "Dress Thrifting Tapi Kelihatan Designer",
    "Kacamata Hitam di Dalam Ruangan",
    "Style Emak-Emak Tapi Bikin Meleleh",
    "Kemeja Flanel Ala Mahasiswi",
    "Hijab Style Bikin Hati Adem",
    "Outfit Ala Anak Skena 2015",
    "Tas Slempang Isi Penuh Makeup",
    "Rambut Gimbal Aesthetic",
    "Kaos Band yang Tidak Pernah Didengar",
    "Sendal Swallow Tapi Gayanya Heels",
    "Hoodie Boba Tapi Bukan Boba",
    "Kemeja Putih Glowing Seperti Tuyul",
    "Rok Plisket Disanggakan Pinggang",
    "Rambut Kepang ala Princess",
    "Outfit Thrifting Tapi Kelihatan Sultan",
    "Jam Tangan Digital ala Anak SD",
    "Kaos Polos Tapi Vibe-nya Mahal",
    "Jeans Ketat Bikin Orang Lupa Jalan",
    "Rambut Keriting Aesthetic Abis",
    "Jaket Bomber dari Zaman SMA",
    "Kaus Kaki Naik ke Mata Kaki",
    "Sneakers Putih Bikin Iri Sekampung",
    "Kacamata Minus Dipakai Pamer",
    "Outfit Hemat Tapi Instagramable",
    "Rambut Lurus ala Cewek K-Drama",
    "Kaos Polo Ala Sales Mobil",
    "Celana Kulot Warna Pastel",
    "Jaket Denim Klasik",
    "Topi Bucket ala Artis Korea",
    "Kemeja Flanel ala Pemburu",
    "Rambut Pendek Berantakan Aesthetic",
    "Sendal Jepit tapi Berjalan Penuh Percaya Diri",
    "Outfit One Set dari Thrift Shop",
    "Tas Totebag Bertuliskan Quotes",
    "Kacamata Anti Radiasi Pameran",
    "Rambut Panjang Berantakan Aesthetic",
    "Kaos Oversize Menutupi Celana",
    "Rok Mini ala Anak Kost",
    "Jam Tangan Pintar Tapi Baterai Habis",
    "Sepatu Flat Shoes Bersih",
    "Cardigan Rajut ala Nenek-nenek",
    "Dress Panjang Berkeliaran Angin",
]

CCANTIK_KEUNGGULAN = [
    "Senyum Bikin Tukang Parkir Lupa Karcis",
    "Tatapan Bikin CCTV Berputar",
    "Muka Bikin Kamera Auto HD",
    "Jalan Dikira Selebgram",
    "Bikin Tetangga Kepo",
    "Aura Positif 1000 Watt",
    "Gagal Jelek Sejak Lahir",
    "Senyum Bikin Hari Jumat Lebih Berkah",
    "Tatapan Bikin Gorden Buka Sendiri",
    "Muka Bikin Warung Tambah Laku",
    "Jalan Bikin Orang Lupa Jalan",
    "Bikin Satpam Komplek Ingin Kenalan",
    "Aura Bikin Galon Air Hangat",
    "Senyum Bikin Tukang Sayur Gratis",
    "Tatapan Bikin Lampu Belajar Lebih Terang",
    "Muka Bikin HP Baterai Awet",
    "Jalan Bikin Macet Jadi Lupa",
    "Bikin Ibu-Ibu Warung Tersipu",
    "Aura Bikin Es Teh Manis Lebih Manis",
    "Senyum Bikin Kucing Ikut Mengeong",
    "Tatapan Bikin Anak SD Pengen Pinter",
    "Muka Bikin Fotografer Jalanan Aktif",
    "Jalan Bikin Orang Lupa Tujuan",
    "Bikin Teman Lama Ingin Reuni",
    "Aura Bikin Pom Bensin Buka 24 Jam",
    "Senyum Bikin Tukang Cilok Gratis",
    "Tatapan Bikin Angin Berhenti Sejenak",
    "Muka Bikin Kamera Depan Jadi HD",
    "Jalan Bikin Jalanan Terasa Runway",
    "Bikin Penjual Martabak Tambah Sayang",
    "Aura Bikin Warteg Ramai Pengunjung",
    "Senyum Bikin Hari Senin Lebih Terang",
    "Tatapan Bikin WiFi Full Bar",
    "Muka Bikin Orang Lupa Marah",
    "Jalan Bikin Jalanan Jadi Panggung",
    "Bikin Teman Sekelas Ingin Contek",
    "Aura Bikin Musim Hujan Jadi Cerah",
    "Senyum Bikin Tukang Sate Tidak Tega Potong",
    "Tatapan Bikin Emak-Emak Terpesona",
    "Muka Bikin Kamera Rusak Jadi Bagus",
    "Jalan Bikin Orang Lupa Waktu",
    "Bikin Tukang Cukur Ingin Gratis",
    "Aura Bikin Indomaret Makin Indah",
    "Senyum Bikin Tukang Tambal Ban Cepat",
    "Tatapan Bikin Lampu Merah Jadi Hijau",
    "Muka Bikin Orang Lupa Hutang",
    "Jalan Bikin Gojek Tepat Waktu",
    "Bikin Tukang Bakso Tanya Nomor",
    "Aura Bikin Galon Jadi Penuh",
    "Senyum Bikin Semua Orang Tersenyum",
    "Gaya Bikin Orang Lupa Kalau Lagi Marah",
    "Pesona Bikin Jalanan Jadi Panggung",
]

CCANTIK_TIER = [
    "PACAR MERTUA",
    "SULTAN KONTRAKAN",
    "CEO WARUNG MADURA",
    "RAJA WIFI RT",
    "PANGERAN KONTER PULSA",
    "KING OF OBLONG",
    "QUEEN KOS-KOSAN",
    "BOS ES TEH",
    "KOMANDAN RONDA",
    "ANAK EMAS WARUNG",
    "PENAKLUK KANTIN",
    "SULTAN GALON",
    "BOSS PARKIR",
    "RAJA JALAN RAYA",
    "SULTAN SPBU",
    "DEWI DISKON SHOPEE",
    "DIREKTUR WARTEG",
    "MANAGER INDOMARET",
    "KOMANDAN PARKIRAN",
    "RAJA NONGKRONG",
    "SULTAN KARCIS",
    "BOSS PARKIR MOTOR",
    "RATU GALON",
    "DIREKTUR KOS-KOSAN",
    "MANAGER ANGKRINGAN",
    "RAJA WIFI GRATIS",
    "SULTAN PULSA",
    "BOSS KANTIN",
    "RATU BASO",
    "DIREKTUR ES TEH",
    "MANAGER TAHU BULAT",
    "RAJA SEBLAK",
    "SULTAN CILOK",
    "BOSS KETOPRAK",
    "RATU MARTABAK",
    "DIREKTUR BAKSO",
    "MANAGER SATE",
    "RAJA NASI GORENG",
    "SULTAN BUBUR AYAM",
    "BOSS GADO-GADO",
    "RATU PEMPEK",
    "DIREKTUR PADANG",
    "MANAGER AYAM GEPREK",
    "RAJA MIE AYAM",
    "SULTAN BAKMI",
    "BOSS SOTO",
    "RATU RONDA MALAM",
    "DIREKTUR KONTER HP",
    "MANAGER WARNET",
    "RAJA JALANAN",
    "SULTAN PARKIRAN",
    "BOSS KANG PARKIR",
]
