"""
IBEKS USERBOT - ID Card Data
Data tambahan untuk ID card: status mental dan label kustom.
Nilai deterministik berdasarkan User ID + minggu ISO saat ini.
"""

STATUS_MENTAL = [
    "Stabil di 2000%",
    "Galau tapi produktif",
    "Overthinking level master",
    "Santai tapi bawah sadar panik",
    "Mode jutek aktif",
    "Hati hancur, tapi tampilan tetap cool",
    "Sibuk padahal lagi rebahan",
    "Pedih tapi pura-pura baik-baik saja",
    "Diam-diam menyerang",
    "Introvert tapi siap membela",
    "Hypebeast akhir bulan",
    "Sok sibuk tapi cuma scroll TikTok",
    "Mode zen tapi otak berisik",
    "Cinta mati sama kopi dan rebahan",
    "Toxic positivity level 99",
    "Pejuang deadline tanpa deadline",
    "Sok cool, padahal sendirian",
    "Main character syndrome",
    "NPC tapi punya storyline sendiri",
    "Stoik tapi gampang terbakar",
    "Mood: random access memory",
    "Senyum sopan, hati menjerit",
    "Bucin tapi paham prioritas",
    "Dewasa karena terpaksa",
    "Healing in progress",
    "Ego besar, hati lembut",
    "Sarkasme adalah bahasa cinta",
    "Tidur larut, bangun siang",
    "Multitasking: rebahan + overthinking",
    "Calm, collected, and slightly unhinged",
    "Glowing karena rehat sosial",
    "Sedang dalam mode 'jangan diganggu'",
    "Chat dibalas dalam hati",
    "Online tapi offline secara emosional",
    "Pede level 100, bukti level 0",
    "Resilience baja tapi mudah nangis",
    "Kolektor masalah orang lain",
    "Sibuk healing dari hal kecil",
    "Otak: 4K, motivasi: 144p",
    "Mode silent treatment aktif",
    "Hidup diatas ekspektasi, tapi lelah",
    "Berbahaya jika sudah tersenyum",
    "Memaafkan tapi tidak melupakan",
    "Pekerja keras di dalam fantasi",
    "Simpel tapi kompleks",
    "Lelah tapi tetap kece",
    "Sedang mencari remote control kehidupan",
    "Kadang sabar, kadang meledak",
    "Full battery, 0% semangat",
    "Mysterious tapi sebenernya cuma malas",
]
